import type { NextPage } from 'next'
import Head from 'next/head'
import DashboardIndex from '../components/Pages/Dashboard/DashboardIndex'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Rect Vision</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardIndex/>
    </div>
  )
}

export default Home
